
OPCOES_CURSOS= (
    (1,u'Administração'),
    (2,u'Agronomia'),
    (3,u'Arquitetura e Urbanismo'),
    (4,u'Biologia'),
    (5,u'Ciência da Computação'),
    (6,u'Ciências Biológicas'),
    (7,u'Ciências Contábeis'),
    (8,u'Ciências Econômicas'),
    (9,u'Ciências Sociais'),
    (10,u'Direito'),
    (11,u'Educação do Campo'),
    (12,u'Educação Física'),
    (13,u'Enfermagem'),
    (14,u'Engenharia Ambiental'),
    (15,u'Engenharia Civil'),
    (16,u'Engenharia de Alimentos'),
    (17,u'Engenharia Bioprocessos e Biotecnologia'),
    (18,u'Engenharia Elétrica'),
    (19,u'Engenharia Florestal'),
    (20,u'Filosofia'),
    (21,u'Física'),
    (22,u'Geografia'),
    (23,u'Gestão de Cooperativas'),
    (24,u'Gestão de Turismo'),
    (25,u'História'),
    (26,u'Jornalismo'),
    (27,u'Letras - Libras'),
    (28,u'Letras - Língua Inglesa / Língua Portuguesa e suas Respectivas Literaturas'),
    (29,u'Letras - Língua Portuguesa e suas Respectivas Literaturas'),
    (30,u'Logística'),
    (31,u'Matemática'),
    (32,u'Medicina'),
    (33,u'Medicina Veterinária'),
    (34,u'Nutrição'),
    (35,u'Pedagogia'),
    (36,u'Psicologia'),
    (37,u'Química'),
    (38,u'Química Ambiental'),
    (39,u'Relações Internacionais'),
    (40,u'Serviço Social'),
    (41,u'Teatro'),
    (42,u'Turismo Patrimonial e Socioambiental'),
    (43,u'Zootecnia'),
)

OPCOES_CAMPUS = (
    (1,u'Câmpus de Araguaína'),
    (2,u'Câmpus de Arrais'),
    (3,u'Câmpus de Gurupi'),
    (4,u'Câmpus de Miracema'),
    (5,u'Câmpus de Palmas'),
    (6,u'Câmpus de Porto Nacional'),
    (7,u'Câmpus de Tocantinópolis'),
)

OPCOES_SITUACAO = (
    (1,u'Evadido'),
    (2,u'Formado'),
    (3,u'Jubilado'),
    (4,u'Vinculado'),
)

OPCOES_INGRESSO = (
    (1,u'PSC'),
    (2,u'PSEnem'),
    (3,u'SISU'),
    (4,u'Vestibular'),
)