# Generated by Django 4.2.5 on 2023-09-22 14:57

import alunos.models.base.Alunos

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoAluno', models.CharField(max_length=100, verbose_name='Nome do Aluno')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('dataNasc', models.DateField(verbose_name='Data de Nascimento')),
                ('foto', models.ImageField(upload_to=alunos.models.base.Alunos.diretorio_imagens_aluno)),
                ('curso', models.SmallIntegerField(choices=[(1, 'Administração'), (2, 'Agronomia'), (3, 'Arquitetura e Urbanismo'), (4, 'Biologia'), (5, 'Ciência da Comupatação'), (6, 'Ciências Biológicas'), (7, 'Ciências Contábeis'), (8, 'Ciências Econômicas'), (9, 'Ciências Sociais'), (10, 'Direito'), (11, 'Educação do Campo'), (12, 'Educação Física'), (13, 'Enfermagem'), (14, 'Engenharia Ambiental'), (15, 'Engenharia Civil'), (16, 'Engenharia de Alimentos'), (17, 'Engenharia Bioprocessos e Biotecnologia'), (18, 'Engenharia Elétrica'), (19, 'Engenharia Florestal'), (20, 'Filosofia'), (21, 'Física'), (22, 'Geografia'), (23, 'Gestão de Cooperativas'), (24, 'Gestão de Turismo'), (25, 'História'), (26, 'Jornalismo'), (27, 'Letras - Libras'), (28, 'Letras - Língua Inglesa / Língua Portuguesa e suas Respectivas Literaturas'), (29, 'Letras - Língua Portuguesa e suas Respectivas Literaturas'), (30, 'Logística'), (31, 'Matemática'), (32, 'Medicina'), (33, 'Medicina Veterinária'), (34, 'Nutrição'), (35, 'Pedagogia'), (36, 'Psicologia'), (37, 'Química'), (38, 'Química Ambiental'), (39, 'Relações Internacionais'), (40, 'Serviço Social'), (41, 'Teatro'), (42, 'Turismo Patrimonial e Socioambiental'), (43, 'Zootecnia')], verbose_name='Curso')),
                ('campus', models.SmallIntegerField(choices=[(1, 'Câmpus de Araguaína'), (2, 'Câmpus de Arrais'), (3, 'Câmpus de Gurupi'), (4, 'Câmpus de Miracema'), (5, 'Câmpus de Palmas'), (6, 'Câmpus de Porto Nacional'), (7, 'Câmpus de Tocantinópolis')], verbose_name='Câmpus')),
                ('situacao', models.SmallIntegerField(choices=[(1, 'Evadido'), (2, 'Formado'), (3, 'Jubilado'), (4, 'Vinculado')], verbose_name='Situação')),
                ('formaDeIngresso', models.SmallIntegerField(choices=[(1, 'PSC'), (2, 'PSEnem'), (3, 'SISU'), (4, 'Vestibular')], verbose_name='Forma de Ingresso')),
                ('matricula', models.CharField(max_length=9, unique=True, verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nomeDoAluno'],
            },
        ),
    ]
