# Generated by Django 4.2.5 on 2023-09-22 17:44

import alunos.models.base.Alunos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.SmallIntegerField(choices=[(1, 'Administração'), (2, 'Agronomia'), (3, 'Arquitetura e Urbanismo'), (4, 'Biologia'), (5, 'Ciência da Computação'), (6, 'Ciências Biológicas'), (7, 'Ciências Contábeis'), (8, 'Ciências Econômicas'), (9, 'Ciências Sociais'), (10, 'Direito'), (11, 'Educação do Campo'), (12, 'Educação Física'), (13, 'Enfermagem'), (14, 'Engenharia Ambiental'), (15, 'Engenharia Civil'), (16, 'Engenharia de Alimentos'), (17, 'Engenharia Bioprocessos e Biotecnologia'), (18, 'Engenharia Elétrica'), (19, 'Engenharia Florestal'), (20, 'Filosofia'), (21, 'Física'), (22, 'Geografia'), (23, 'Gestão de Cooperativas'), (24, 'Gestão de Turismo'), (25, 'História'), (26, 'Jornalismo'), (27, 'Letras - Libras'), (28, 'Letras - Língua Inglesa / Língua Portuguesa e suas Respectivas Literaturas'), (29, 'Letras - Língua Portuguesa e suas Respectivas Literaturas'), (30, 'Logística'), (31, 'Matemática'), (32, 'Medicina'), (33, 'Medicina Veterinária'), (34, 'Nutrição'), (35, 'Pedagogia'), (36, 'Psicologia'), (37, 'Química'), (38, 'Química Ambiental'), (39, 'Relações Internacionais'), (40, 'Serviço Social'), (41, 'Teatro'), (42, 'Turismo Patrimonial e Socioambiental'), (43, 'Zootecnia')], verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=alunos.models.base.Alunos.diretorio_imagens_aluno),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(editable=False, max_length=9, unique=True, verbose_name='Matrícula'),
        ),
    ]
