# Generated by Django 4.2.5 on 2023-09-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('campus', '0001_initial'),
        ('alunos', '0002_alter_aluno_curso_alter_aluno_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campus.campus'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.curso'),
        ),
    ]
