# Generated by Django 4.2.5 on 2023-09-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Câmpus')),
            ],
            options={
                'verbose_name': 'Câmpus',
                'verbose_name_plural': 'Câmpus',
                'ordering': ['nome'],
            },
        ),
    ]
