# Generated by Django 4.2.5 on 2023-09-25 18:58

import academico.models.base.Alunos
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Câmpus')),
            ],
            options={
                'verbose_name': 'Câmpus',
                'verbose_name_plural': 'Câmpus',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Curso')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.campus', verbose_name='Câmpus')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDoAluno', models.CharField(max_length=100, verbose_name='Nome do Aluno')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('dataNasc', models.DateField(verbose_name='Data de Nascimento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to=academico.models.base.Alunos.diretorio_imagens_aluno)),
                ('situacao', models.SmallIntegerField(choices=[(1, 'Evadido'), (2, 'Formado'), (3, 'Jubilado'), (4, 'Vinculado')], verbose_name='Situação')),
                ('formaDeIngresso', models.SmallIntegerField(choices=[(1, 'PSC'), (2, 'PSEnem'), (3, 'SISU'), (4, 'Vestibular')], verbose_name='Forma de Ingresso')),
                ('matricula', models.CharField(editable=False, max_length=9, unique=True, verbose_name='Matrícula')),
                ('campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.campus')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.curso')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nomeDoAluno'],
            },
        ),
    ]
